github:
    # The name of your project on github
    repository: your-awesome-project
    # The owner of the project on github
    owner: official-owner
    # The owner of the user who will create pull requests with new translations
    fork_owner: crowdin-bot
    # The github token of this user
    token: 123456789abcdef123456789abcdef123456789a
    # The branches to manage. Use [~] if you don't want branch management. Default: ['master']
    branches: ['master', '1.0', '2.0']

crowdin:
    # The name of your project on Crowdin
    project: your-awesome-project
    # The key of your project on Crowdin
    key: 123456789abcdef123456789abcdef12
    # You can set a minimum to only pull full-translated languages (from 0 to 100, default: 0)
    min_translated_progress: 0
    download:
        base_dir: /tmp/nelson-download
        # By default, specific region languages are removed; mapping is done by the 2 first letters.
        # Insert here special mappings, like this:
        locale_map:
            fr_FR: fr
            fr_BE: fr_BE
    upload:
        base_dir: /tmp/nelson-upload

nelson:
    # These options are passed to a Symfony Finder to find your original translation files.
    # Be careful, only select your origin language files (for example, only *.en.yml files).
    finder_options:
        in: 'src/'
        notPath: '/not_translated_folder/'
        path: '/Resources\/translations/'
        name: '*.en.yml'
    # You can map your github project file paths to crowdin file paths. These next parameters are used in
    # a str_replace function.
    target_rules:
        '/Resources/translations': ''
        'src/YourAwesomeProject/Bundle': 'YourAwesomeProject'
    # Optional: You can put your translations in a folder when you download archive from Crowdin.
    # Can be useful when your Crowdin project is linked to several github repositories.
    pattern_suffix: 'Community'
    # Optional: log the application executions in this file.
    log_file: 'app/logs/application.log'
    # Optional: translate logs. Default: 'en_US'
    log_locale: 'fr_FR'
